from aiogram.fsm.state import State, StatesGroup

class Form(StatesGroup):
    consent = State()
    explanation = State()
    name = State()
    gender = State()
    age = State()
    height = State()
    weight = State()
    body_type = State()
    activity = State()
    occupation = State()
    allergies = State()
    meals_per_day = State()
    water_per_day = State()
    sleep_schedule = State()
    sleep_quality = State()
    physical_activity = State()
    symptoms = State()
    goal = State()
    food_preferences = State()
    difficulties = State()
    diseases = State()
    medications = State()
    supplements = State()
    calculations = State()
    recommendations = State()
    final = State()

class Diary(StatesGroup):
    waiting_for_product = State()
    waiting_for_quantity = State()
    waiting_for_new_product = State()
    waiting_for_new_product_calories = State()
    waiting_for_new_product_protein = State()
    waiting_for_new_product_fat = State()
    waiting_for_new_product_carbs = State()